services:
  openmrs-gateway:
    image: openmrs/openmrs-reference-application-3-gateway:${TAG:-qa}
    configs:
      - target: /etc/nginx/templates/default.conf.template
        source: openmrs-gateway.conf
    networks:
      - openmrs_default
      - reverse-proxy_public

configs:
  openmrs-gateway.conf:
    name: openmrs-gateway-conf-${OPENMRS_GATEWAY_CONF_DIGEST:?err}
    file: ./config/default.conf.template
    labels:
      name: openmrs-gateway

networks:
  openmrs_default:
    name: openmrs_default
    external: true
  reverse-proxy_public:
    name: reverse-proxy_public
    external: true