projectName: omrs-ai-playground
image: omrs-ai-playground:latest
logPath: /tmp/logs

packages:
  - database-mysql
  - emr-openmrs
  - redis
  - omrs-appo-service
  - reverse-proxy-nginx
  - analytics-ohs-data-pipes
  - fhir-datastore-hapi-fhir
  - med-agent-hub


