services:
  omrs-appo-service:
    image: ${OMRS_APPO_SERVICE_IMAGE:-omrs-appo-service:latest}
    hostname: omrs-appo-service
    container_name: omrs-appo-service
    networks:
      - instant
    ports:
      - "8000:8000"
    environment:
      WHATSAPP_API_KEY: ${WHATSAPP_API_KEY}
      WHATSAPP_PHONE_NUMBER_ID: ${WHATSAPP_PHONE_NUMBER_ID}
      WHATSAPP_WEBHOOK_VERIFY_TOKEN: ${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
      WHATSAPP_ACCESS_TOKEN: ${WHATSAPP_ACCESS_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      MEDGEMMA_MODEL: ${MEDGEMMA_MODEL}
      OPENMRS_BASE_URL: ${OPENMRS_BASE_URL}
      REDIS_URL: ${REDIS_URL}
      OPENMRS_USERNAME: ${OPENMRS_USERNAME}
      OPENMRS_PASSWORD: ${OPENMRS_PASSWORD}
      SERVICE_PORT: ${SERVICE_PORT}
      SERVICE_HOST: ${SERVICE_HOST}
      LOG_LEVEL: ${LOG_LEVEL}
      ENVIRONMENT: ${ENVIRONMENT}
      WEBHOOK_BASE_URL: ${WEBHOOK_BASE_URL}
    depends_on:
      - openmrs
      - redis
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 