services:
  hapi-synthea-loader:
    image: ${SYNTHEA_UPLOADER_IMAGE}
    environment:
      TARGET: HAPI
      BASE_URL: http://hapi-fhir:8080/fhir
      DATASET: full
      CORES: 6
    networks:
      - default
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: none

networks:
  default:
  postgres:
    name: postgres_public
    external: true

